/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.contabilidad.pcga;

import j2o.software.kraken.db.model.general.Empresa;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity
@Table(name="conta_pcga_centro_costo")
@NamedQueries({@NamedQuery(name="CentroCosto.findAllByEmpresa",query="Select c from CentroCosto c where c.empresa.id=:empresa"),@NamedQuery(name="CentroCosto.findAllByEmpresaAndCodigo",query="Select c from CentroCosto c where c.empresa.id=:empresa and c.codigo=:codigo")})
public class CentroCosto implements Serializable { 

    @Column(name="cc_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="cc_codigo")
    @Basic
    private String codigo;

    @Column(name="cc_nombre")
    @Basic
    private String nombre;

    @Column(name="cc_pertenece")
    @Basic
    private String pertenece;

    @Column(name="cc_nivel")
    @Basic
    private String nivel;

    @Column(name="cc_fecha_final")
    @Basic
    private String nivelFinal;

    @Column(name="cc_fecha")
    @Basic
    private Date fecha;

    @ManyToOne(targetEntity = Empresa.class)
    @JoinColumn(name="CC_EMPRESA_ID")
    private Empresa empresa;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getPertenece() {
        return this.pertenece;
    }

    public void setPertenece(String pertenece) {
        this.pertenece = pertenece;
    }

    public String getNivel() {
        return this.nivel;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public String getNivelFinal() {
        return this.nivelFinal;
    }

    public void setNivelFinal(String nivelFinal) {
        this.nivelFinal = nivelFinal;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }


}
