/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.contabilidad.pcga;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;


@Entity
public class DetalleDocumento implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String naturaleza;

    @Basic
    private String acreedora;

    @ManyToOne(targetEntity = TipoDocumento.class)
    private TipoDocumento tipoDocumento;

    @ManyToOne(targetEntity = PlanUnicoCuentas.class)
    private PlanUnicoCuentas planUnicoCuentas;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNaturaleza() {
        return this.naturaleza;
    }

    public void setNaturaleza(String naturaleza) {
        this.naturaleza = naturaleza;
    }

    public String getAcreedora() {
        return this.acreedora;
    }

    public void setAcreedora(String acreedora) {
        this.acreedora = acreedora;
    }

    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }

    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public PlanUnicoCuentas getPlanUnicoCuentas() {
        return this.planUnicoCuentas;
    }

    public void setPlanUnicoCuentas(PlanUnicoCuentas planUnicoCuentas) {
        this.planUnicoCuentas = planUnicoCuentas;
    }


}
