/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.contabilidad.pcga;

import j2o.software.kraken.db.model.general.Tercero;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;


@Entity
public abstract class DetalleAsiento implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Basic(optional=false)
    private double valorDB;

    @Basic
    private Double valorCR;

    @Basic
    private String descrpcion;

    @Basic
    private String valorBase;

    @Basic
    private Double valorTasa;

    @ManyToOne(targetEntity = Tercero.class)
    private Tercero tercero;

    @ManyToOne(targetEntity = AsientoContable.class)
    private AsientoContable asientoContable;

    @ManyToOne(targetEntity = CentroCosto.class)
    private CentroCosto centroCosto;

    @ManyToOne(targetEntity = Naturaleza.class)
    private Naturaleza naturaleza;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getValorDB() {
        return this.valorDB;
    }

    public void setValorDB(double valorDB) {
        this.valorDB = valorDB;
    }

    public Double getValorCR() {
        return this.valorCR;
    }

    public void setValorCR(Double valorCR) {
        this.valorCR = valorCR;
    }

    public String getDescrpcion() {
        return this.descrpcion;
    }

    public void setDescrpcion(String descrpcion) {
        this.descrpcion = descrpcion;
    }

    public String getValorBase() {
        return this.valorBase;
    }

    public void setValorBase(String valorBase) {
        this.valorBase = valorBase;
    }

    public Double getValorTasa() {
        return this.valorTasa;
    }

    public void setValorTasa(Double valorTasa) {
        this.valorTasa = valorTasa;
    }

    public Tercero getTercero() {
        return this.tercero;
    }

    public void setTercero(Tercero tercero) {
        this.tercero = tercero;
    }

    public AsientoContable getAsientoContable() {
        return this.asientoContable;
    }

    public void setAsientoContable(AsientoContable asientoContable) {
        this.asientoContable = asientoContable;
    }

    public CentroCosto getCentroCosto() {
        return this.centroCosto;
    }

    public void setCentroCosto(CentroCosto centroCosto) {
        this.centroCosto = centroCosto;
    }

    public Naturaleza getNaturaleza() {
        return this.naturaleza;
    }

    public void setNaturaleza(Naturaleza naturaleza) {
        this.naturaleza = naturaleza;
    }


}
