/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.contabilidad.pcga;

import j2o.software.kraken.db.model.general.Empresa;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity
@Table(name="conta_pcga_periodo")
@NamedQueries({@NamedQuery(name="Periodo.findAllByEmpresa",query="Select p from Periodo p where p.empresa.id=:empresa"),@NamedQuery(name="Periodo.findAllByEmpresaAndAnyoAndMes",query="Select p from Periodo p where p.empresa.id=:empresa and p.anyo=:anyo and p.mes=:mes")})
public class Periodo implements Serializable { 

    @Column(name="periodo_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="periodo_anyo")
    @Basic
    private String anyo;

    @Column(name="periodo_mes")
    @Basic
    private String mes;

    @Column(name="periodo_estado")
    @Basic
    private String estado;

    @Column(name="periodo_fecha_apertura")
    @Basic
    private Date fechaApertura;

    @Column(name="periodo_fecha_cierre")
    @Basic
    private Date fechaCierre;

    @ManyToOne(targetEntity = Empresa.class)
    @JoinColumn(name="PERIODO_EMPRESA_ID")
    private Empresa empresa;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAnyo() {
        return this.anyo;
    }

    public void setAnyo(String anyo) {
        this.anyo = anyo;
    }

    public String getMes() {
        return this.mes;
    }

    public void setMes(String mes) {
        this.mes = mes;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaApertura() {
        return this.fechaApertura;
    }

    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }

    public Date getFechaCierre() {
        return this.fechaCierre;
    }

    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }


}
