/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.contabilidad.pcga;

import j2o.software.kraken.db.model.general.Empresa;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity
@Table(name="conta_pcga_puc")
@NamedQueries({@NamedQuery(name="PlanUnicoCuentas.findAllByEmpresa",query="Select p from PlanUnicoCuentas p where p.empresa.id=:empresa"),@NamedQuery(name="PlanUnicoCuentas.findAllByEmpresaAndCuenta",query="Select p from PlanUnicoCuentas p where p.empresa.id=:empresa and p.cuenta=:cuenta")})
public class PlanUnicoCuentas implements Serializable { 

    @Column(name="puc_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="puc_cuenta")
    @Basic
    private String cuenta;

    @Column(name="puc_pertenece")
    @Basic
    private String pertenece;

    @Column(name="puc_nombre")
    @Basic
    private String nombre;

    @Column(name="puc_naturaleza")
    @Basic
    private String naturaleza;

    @Column(name="puc_nivel")
    @Basic
    private String nivel;

    @Column(name="puc_auxiliar")
    @Basic
    private String auxiliar;

    @Column(name="puc_fecha")
    @Basic
    private Date fecha;

    @ManyToOne(targetEntity = Empresa.class)
    @JoinColumn(name="PUC_EMPRESA_ID")
    private Empresa empresa;

    @ManyToOne(targetEntity = Clase.class)
    @JoinColumn(name="PUC_CLASE_ID")
    private Clase clase;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCuenta() {
        return this.cuenta;
    }

    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }

    public String getPertenece() {
        return this.pertenece;
    }

    public void setPertenece(String pertenece) {
        this.pertenece = pertenece;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getNaturaleza() {
        return this.naturaleza;
    }

    public void setNaturaleza(String naturaleza) {
        this.naturaleza = naturaleza;
    }

    public String getNivel() {
        return this.nivel;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public String getAuxiliar() {
        return this.auxiliar;
    }

    public void setAuxiliar(String auxiliar) {
        this.auxiliar = auxiliar;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Clase getClase() {
        return this.clase;
    }

    public void setClase(Clase clase) {
        this.clase = clase;
    }


}
