/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.contabilidad.pcga;

import j2o.software.kraken.db.general.Tercero;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;


@Entity
public abstract class DetalleAsiento implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Basic
    private String naturaleza;

    @Basic(optional=false)
    private double valorDB;

    @Basic
    private int valorCR;

    @Basic
    private String descrpcion;

    @ManyToOne(targetEntity = Tercero.class)
    private Tercero tercero;

    @ManyToOne(targetEntity = AsientoContable.class)
    private AsientoContable asientoContable;

    @ManyToOne(targetEntity = CentroCosto.class)
    private CentroCosto centroCosto;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNaturaleza() {
        return this.naturaleza;
    }

    public void setNaturaleza(String naturaleza) {
        this.naturaleza = naturaleza;
    }

    public double getValorDB() {
        return this.valorDB;
    }

    public void setValorDB(double valorDB) {
        this.valorDB = valorDB;
    }

    public int getValorCR() {
        return this.valorCR;
    }

    public void setValorCR(int valorCR) {
        this.valorCR = valorCR;
    }

    public String getDescrpcion() {
        return this.descrpcion;
    }

    public void setDescrpcion(String descrpcion) {
        this.descrpcion = descrpcion;
    }

    public Tercero getTercero() {
        return this.tercero;
    }

    public void setTercero(Tercero tercero) {
        this.tercero = tercero;
    }

    public AsientoContable getAsientoContable() {
        return this.asientoContable;
    }

    public void setAsientoContable(AsientoContable asientoContable) {
        this.asientoContable = asientoContable;
    }

    public CentroCosto getCentroCosto() {
        return this.centroCosto;
    }

    public void setCentroCosto(CentroCosto centroCosto) {
        this.centroCosto = centroCosto;
    }


}
