/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.general;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity(name="Representante")
@Table(name="gen_representante")
@NamedQuery(name="Representante.findAllByEmpresa",query="Select r from Representante r where r.empresa.id =:empresa")
public class Representante implements Serializable { 

    @Column(name="rep_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="rep_identificacion")
    @Basic
    private String identificacion;

    @Column(name="rep_nombre")
    @Basic
    private String nombres;

    @Column(name="rep_apellidos")
    @Basic
    private String apellidos;

    @ManyToOne(targetEntity = Empresa.class)
    @JoinColumn(name="REP_EMPRESA_ID")
    private Empresa empresa;

    @ManyToOne(targetEntity = TipoIdentificacion.class)
    @JoinColumn(name="REP_TI_ID")
    private TipoIdentificacion tipoIdentificacion;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentificacion() {
        return this.identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public TipoIdentificacion getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }

    public void setTipoIdentificacion(TipoIdentificacion tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }


}
