/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.model.general;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jdmp
 */

@Entity
@Table(name="gen_tipo_contribuyente")
@NamedQuery(name="TipoContribuyente.findAllByCodigo",query="Select t from TipoContribuyente t where t.codigo=:codigo")
public class TipoContribuyente { 

    @Column(name="tip_contri_id")
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    @Column(name="tip_contri_codigo")
    @Basic
    private String codigo;

    @Column(name="tip_contri_nombre")
    @Basic
    private String nombre;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


}
