/**
 * This file was generated by the JPA Modeler
 */
package j2o.software.kraken.db;

import java.io.Serializable;
import j2o.software.kraken.db.contabilidad.pcga.Empresa;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity
@Table(name = "sec_permiso")
public class Permiso implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToMany(targetEntity = Usuario.class)
    @JoinColumn(name = "USUARIO_ID")
    private List<Usuario> usuario;

    @OneToMany(targetEntity = Rol.class)
    @JoinColumn(name = "ROL_ID")
    private List<Rol> rol;

    @OneToMany(targetEntity = Empresa.class)
    @JoinColumn(name = "EMPRESA_ID")
    private List<Empresa> empresa;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<Usuario> getUsuario() {
        return this.usuario;
    }

    public void setUsuario(List<Usuario> usuario) {
        this.usuario = usuario;
    }

    public List<Rol> getRol() {
        return this.rol;
    }

    public void setRol(List<Rol> rol) {
        this.rol = rol;
    }

    public List<Empresa> getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(List<Empresa> empresa) {
        this.empresa = empresa;
    }

}
