/**
 * This file was generated by the JPA Modeler
 */
package j2o.software.kraken.db;

import java.io.Serializable;
import j2o.software.kraken.db.contabilidad.pcga.Tercero;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * @author jkelsy
 */
@Entity
@Table(name = "sec_usuario")
public class Usuario implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String login;

    @Basic
    private String password;

    @Basic
    private boolean activo;

    @OneToMany(targetEntity = Tercero.class)
    @JoinColumn(name = "TERCERO_ID")
    private List<Tercero> tercero;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isActivo() {
        return this.activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public List<Tercero> getTercero() {
        return this.tercero;
    }

    public void setTercero(List<Tercero> tercero) {
        this.tercero = tercero;
    }

}
