/**
 * This file was generated by the JPA Modeler
 */ 

package j2o.software.kraken.db.general;

import j2o.software.kraken.db.seguridad.Usuario;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;


@Entity
@Table(name="conf_empresa")
public class Empresa implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Basic
    private String identificacion;

    @Basic
    private String nombre;

    @Basic
    private String direccion;

    @Basic
    private String telefono;

    @Basic
    private String email;

    @OneToMany(targetEntity = Usuario.class)
    @JoinColumn(name="CREADO_POR")
    private List<Usuario> creado_por;


    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentificacion() {
        return this.identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public List<Usuario> getCreado_por() {
        return this.creado_por;
    }

    public void setCreado_por(List<Usuario> creado_por) {
        this.creado_por = creado_por;
    }


}
